esphome:
  name: gate
  friendly_name: GATE

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "<YOU_KEY"

ota:
  password: "<YOU_OTA_PASSWORD>"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gate Fallback Hotspot"
    password: "<YOU_FAILBACK_PASSWORD>"

captive_portal:

########################################

status_led:
 pin: 13

binary_sensor:

# Кнопка 1
  - platform: gpio
    pin:
      number: 9
      mode: INPUT_PULLUP
      inverted: true
    name: "button1"
    id: button1

# Нажатие кнопки1 переключает реле1
    on_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - switch.turn_on: relay1
        - delay: 350ms
        - switch.turn_off: relay1
        - delay: 350ms
        - switch.turn_off: relay1


# Кнопка 2
  - platform: gpio
    pin:
      number: 0
      mode: INPUT_PULLUP
      inverted: true
    name: "button2"
    id: button2

# Нажатие кнопки2 переключает реле2
    on_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - switch.turn_on: relay2
        - delay: 350ms
        - switch.turn_off: relay2
        - delay: 350ms
        - switch.turn_off: relay2


switch:
# Реле 1
  - platform: gpio
    name: "relay1"
    pin: GPIO12
    id: relay1
    icon: "mdi:gate"
    interlock: [relay2]
    on_turn_on:
    - delay: 350ms
    - switch.turn_off: relay1

# Реле 2
  - platform: gpio
    name: "relay2"
    pin: GPIO5
    id: relay2
    icon: "mdi:gate-open"
    interlock: [relay1]
    on_turn_on:
    - delay: 350ms
    - switch.turn_off: relay2

